global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'blockscout'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.0.45:35003']
        labels:
          instance: 'blockscout-dev'